const dataMusic = [
  {
    id: '1',
    artist: 'I Am They',
    track: 'Promises',
    poster: 'images/I-am-they.jpg',
    mp3: 'audio/I Am They - Promises.mp3',
  },
  {
    id: '2',
    artist: 'Hillsong Worship',
    track: 'All For Love',
    poster: 'images/hillsongworship.jpg',
    mp3: 'audio/All For Love - Hillsong Worship.mp3',
  },
  {
    id: '3',
    artist: 'Belonging Co',
    track: 'By The Blood',
    poster: 'images/The-Belonging-Co.jpg',
    mp3: 'audio/By The Blood The Belonging Co.mp3',
  },
  {
    id: '4',
    artist: 'Chris Tomlin',
    track: 'Goodness, Love And Mercy',
    poster: 'images/Chris-Tomlin-cr-Robby-Klein.jpg',
    mp3: 'audio/Chris Tomlin - Goodness, Love And Mercy.mp3',
  },
  {
    id: '5',
    artist: 'Hillsong Young & Free',
    track: 'Let Go',
    poster: 'images/hillsong-yf.jpg',
    mp3: 'audio/Let Go - Hillsong Young & Free.mp3',
  },
  {
    id: '6',
    artist: 'TobyMac',
    track: 'See The Light',
    poster: 'images/TobyMac.jpg',
    mp3: 'audio/TobyMac - See The Light.mp3',
  },
  {
    id: '7',
    artist: 'Planetshakers',
    track: "For all You've done",
    poster: 'images/Planetshakers.jpg',
    mp3: "audio/Planetshakers- For all You've done.mp3",
  },
  {
    id: '8',
    artist: 'Elevation Worship',
    track: 'Echo',
    poster: 'images/Elevation Worship-Echo.jpg',
    mp3: 'audio/Echo Live  Elevation Worship.mp3',
  },
  {
    id: '9',
    artist: 'Chris Tomlin',
    track: 'Holy Forever',
    poster: 'images/chris-tomlin.jpg',
    mp3: 'audio/Chris Tomlin - Holy Forever.mp3',
  },
  {
    id: '10',
    artist: 'Tauren Wells',
    track: 'God\'s Not Done With You',
    poster: 'images/Tauren-Wells.jpg',
    mp3: 'audio/Tauren Wells - God\'s Not Done With You.mp3',
  },
  {
    id: '11',
    artist: 'Michael W. Smith',
    track: 'You Wont Let Go',
    poster: 'images/Michael-W.Smith.jpg',
    mp3: 'audio/Michael W. Smith - You Wont Let Go.mp3',
  },
  {
    id: '12',
    artist: 'Lincoln Brewster',
    track: 'Your Love Is Amazing',
    poster: 'images/Lincoln-Brewster.jpg',
    mp3: 'audio/Lincoln Brewster - Your Love Is Amazing.mp3',
  },
];

